version: "3.8"

services:
  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: gateway_cache
    ports:
      - "6379:6379"

  # Gateway service
  gateway:
    build: .
    container_name: gateway_service
    ports:
      - "8080:8000"
    environment:
      - CACHE_URL=redis://redis:6379
      - CACHE_DEFAULT_TTL=15
      # Dummy targets just for testing
      - TOWN_SERVICE_URL=http://example.com
      - CHARACTER_SERVICE_URL=http://example.com
    depends_on:
      - redis
